
name: Daily Data Update

on:
  schedule:
    - cron: "0 14 * * *"  # Runs daily (UTC time) I *think* this means it updates at 2-3am NZT
  workflow_dispatch:      # lets you run it manually

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run script
        run: node update-data.js

      - name: Commit updated file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/roads.geojson
          git add data/footpaths.geojson
          git commit -m "Update GeoJSON data" || echo "No changes"
          git push
